Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@slowy07 
kloter2surga
/
java
1
0
1
Code
Issues
Pull requests
1
Actions
Projects
Wiki
Security
Insights
Settings
java/.circleci/config.yml
@slowy07
slowy07 Update config.yml
Latest commit 1f5b07c 4 minutes ago
 History
 2 contributors
@slowy07@prettifier
30 lines (24 sloc)  788 Bytes
 
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies